#!/usr/bin/bash

SRC=$HOME/apps
TARGET=rpi4
MEGA=mega://fmount@mega.nz
LOG="$HOME/.duplicity/notice.log"
IGNORE="$HOME/.duplicity/ignore"
CLEAN=0


function init() {
    [ ! -d "$HOME/.duplicity" ] && mkdir -p "$HOME/.duplicity"
    for i in notice.log ignore; do
        if [ ! -f "$HOME/.duplicity/$i" ]; then
                echo "NOT FOUND"
                touch "$HOME/.duplicity/$i"
        fi
    done
    [ -z "$HOME/.duplicity" ] && mkdir -p "$HOME/.duplicity"
}
function backup() {
    #duplicity backup --verbosity notice --full-if-older-than 1M --log-file "${LOG}" --exclude-filelist "${IGNORE}" "${SRC}" ${MEGA}/${TARGET}
    duplicity --verbosity notice full --progress --log-file "${LOG}" --exclude-filelist "${IGNORE}" "${SRC}" ${MEGA}/${TARGET}
}

function restore() {
    echo "Restoring backup"
    duplicity restore "${SRC}" ${MEGA}/${TARGET}
}

function cleanup() {
    local days=${days:-7D}
    duplicity remove-older-than "$days ${MEGA}/${TARGET}"
}

init
backup
[ "${CLEAN}" -eq 1 ] && cleanup

# CHECK
# duplicity collection-status --progress mega://fmount@mega.nz/rpi4
