#!/usr/bin/bash

echo "Backup duplicity job"
# s3 params
export AWS_ACCESS_KEY_ID=''
export AWS_SECRET_ACCESS_KEY=''

# gpg pub key
export GPG_KEY='1FCA0620'
export GPG_SIGN_KEY='C66B3D3F'

RSYNC=$(command -v rsync)
#RPI_HOST=""
#RPI_USER=""
TARGET="$HOME/backup"


function dupl() {
    source=""  # what I want to backup
    bucket="" # destination (target), where I want to put my enc files

    user=""
    psw=""

    duplicity --verbosity notice --encrypt-key "$GPG_KEY" --sign-key "$GPG_SIGN_KEY" \
        --full-if-older-than 7D --asynchronous-upload --volsize=100 --log-file \
        "$HOME/.duplicity/notice.log" $source mega://$user:$psw@mega.nz/$bucket

}

function rPi() {

    sudo "$RSYNC" "$RPI_USER"@"$RPI_HOST":/ -avzP --numeric-ids \
        --exclude={"/dev/*","/boot/*","/proc/*","/sys/*","/tmp/*", \
        "/run/*","/mnt/*","/media/*","/lost+found","swapfile","/var/*"} \
        "$TARGET"
}
