#!/usr/bin/env bash

shopt -s nullglob globstar

GPGAGENTHOME=~/.gnupg/gpg-agent.conf

function reload_agent(){
	rl=$(gpg-connect-agent reloadagent /bye)
	
	case $rl in
		OK) 
		 sleep 1;
		 ;;
		 *)
		 ;;
	esac
}


function agent_profile_toggle(){
	if [ $# -eq 0 ]; then
		echo "::ERROR"
	else
		# Change gpg configuration and reload the agent
		sed -i "s/'$1'/'$2'/g" $GPGAGENTHOME
		
		#Reload gpg-agent
		reload_agent
	fi
}


typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu -b "$@")

[[ -n $password ]] || exit

agent_profile_toggle "curses" "gtk"

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else

	pass show "$password" | { read -r pass; printf %s "$pass"; } | 
		xdotool type --clearmodifiers --file -
	
fi

agent_profile_toggle "gtk" "curses"
