#!/bin/env bash

TARGET="Master"
FILTER="Front\ Left\:"
PROVIDER="pulse"
DISABLED="[mute]"

is_enabled() {
	local ena
	#ena=$(amixer -D "${PROVIDER}" get "${TARGET}" | awk ' /Front\ Left\:/ {print $6}' | tr '[|]' ' ')
	ena=$(amixer get "${TARGET}" | awk ' /Mono/ {print $4}' | tr '[|]' ' ')
	echo $ena
}


VOL_VALUE=$(is_enabled)
case ${VOL_VALUE} in
	"on")
		#amixer -D "${PROVIDER}" get "${TARGET}" | awk ' /Front\ Left\:/ {print $5}' | tr '[|]' ' ' 
		amixer get "${TARGET}" | awk ' /Mono/ {print $4}' | tr '[|]' ' ' 
		;;
	"off")
		a="$(amixer -D "${PROVIDER}" get "${TARGET}" | awk ' /Mono/ {print $4}' | tr '[|]' ' ')"
		tput setaf 1; echo -n "$a [mute]"
		;;
	"default")
		echo "ERROR!"
		;;
esac
