#!/bin/sh

#!/bin/sh
#AccuWeather (r) RSS weather tool for conky
#
#USAGE: weather.sh <locationcode>
#
#(c) Michael Seiler 2007

METRIC=1 #Should be 0 or 1; 0 for F, 1 for C
#locCode=95041
#locCode="EUR|IT|IT248|TORINO"
#locCode="venaria%20reale"
#locCode="torino"

#TODO: BUG: Not work with location name with spaces such as "Venaria Reale". So we have to check for
#any space and transform it in %20: curl will thanks us! :D

locCode=$1

if [ -z $1 ]; then
    echo
    echo "USAGE: weather.sh <locationcode>"
    echo
    exit 0;
fi

curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=${locCode} | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }'

